version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.mongo:/data/db

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/example
    volumes:
      - ./.neo4j:/data
